#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Laraveles Lang Installer', '1.0.0');

$app->add(new Laraveles\Lang\Installer\Console\AddCommand());

$app->run();
